name: Build and Dockerize Microservices

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        project: [ProductService, UserService, OrderService, InventoryService, NotificationService]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore ./src/${{ matrix.project }}/${{ matrix.project }}.csproj

    - name: Build
      run: dotnet build --no-restore ./src/${{ matrix.project }}/${{ matrix.project }}.csproj

    - name: Test (skip if no tests for now)
      run: echo "No tests yet for ${{ matrix.project }}"

    - name: Build Docker image
      run: |
        docker build -t ghcr.io/${{ github.repository_owner }}/${{ matrix.project }}:latest ./src/${{ matrix.project }}
