name: Build and Dockerize Microservices

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        project:
          - ProductService
          - UserService
          - OrderService
          - InventoryService
          - NotificationService

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debug: list workspace
        run: |
          echo "=== workspace root ==="
          ls -R .
          echo
          echo "=== src/ ==="
          ls src
          echo
          echo "=== src/${{ matrix.project }} ==="
          ls src/${{ matrix.project }} || echo ">> folder not found!"

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore src/${{ matrix.project }}/${{ matrix.project }}.csproj

      - name: Build project
        run: dotnet build --no-restore src/${{ matrix.project }}/${{ matrix.project }}.csproj

      - name: Test placeholder
        run: echo "No tests yet for ${{ matrix.project }}"

      - name: Set fully lowercase image name
        run: |
          IMAGE_TAG="ghcr.io/$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')/$(echo '${{ matrix.project }}' | tr '[:upper:]' '[:lower:]')"
          echo "IMAGE_NAME=$IMAGE_TAG" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build \
            --file "${{ github.workspace }}/src/${{ matrix.project }}/Dockerfile" \
            --tag "$IMAGE_NAME" \
            "${{ github.workspace }}/src/${{ matrix.project }}"
