# .github/workflows/build.yml
name: Build & Push Docker Images

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  packages: write
  id-token: write

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - service:       InventoryService
            api-dir:       src/InventoryService/InventoryService.API
            tag-suffix:    inventoryservice
          - service:       NotificationService
            api-dir:       src/NotificationService/NotificationService.API
            tag-suffix:    notificationservice
          - service:       OrderService
            api-dir:       src/OrderService/OrderService.API
            tag-suffix:    orderservice
          - service:       ProductService
            api-dir:       src/ProductService/ProductService.API
            tag-suffix:    productservice
          - service:       UserService
            api-dir:       src/UserService/UserService.API
            tag-suffix:    userservice

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU (for multi-platform)
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Lowercase the repo owner
        run: |
          echo "OWNER_LOWER=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Build & push ${{ matrix.service }}
        uses: docker/build-push-action@v4
        with:
          context: ${{ matrix.api-dir }}
          file:    Dockerfile
          push:    true
          tags: |
            ghcr.io/${{ env.OWNER_LOWER }}/${{ matrix.tag-suffix }}:latest
            ghcr.io/${{ env.OWNER_LOWER }}/${{ matrix.tag-suffix }}:${{ github.sha }}
