name: Build & Push Docker Images

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - service:       InventoryService
            api-dir:       src/InventoryService/InventoryService.API
            tag-suffix:    inventoryservice
          - service:       NotificationService
            api-dir:       src/NotificationService/NotificationService.API
            tag-suffix:    notificationservice
          - service:       OrderService
            api-dir:       src/OrderService/OrderService.API
            tag-suffix:    orderservice
          - service:       ProductService
            api-dir:       src/ProductService/ProductService.API
            tag-suffix:    productservice
          - service:       UserService
            api-dir:       src/UserService/UserService.API
            tag-suffix:    userservice

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push ${{ matrix.service }}
        uses: docker/build-push-action@v4
        with:
          context:    ${{ matrix.api-dir }}
          file:       ${{ matrix.api-dir }}/Dockerfile
          push:       true
          tags:       |
            ghcr.io/${{ github.repository_owner }}/${{ matrix.tag-suffix }}:latest
            ghcr.io/${{ github.repository_owner }}/${{ matrix.tag-suffix }}:${{ github.sha }}
