name: Build and Dockerize Microservices

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        project:
          - ProductService
          - UserService
          - OrderService
          - InventoryService
          - NotificationService

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Build .NET project
        run: dotnet build --no-restore src/${{ matrix.project }}/${{ matrix.project }}.csproj

      - name: Compute image name
        run: |
          IMAGE_TAG="ghcr.io/$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')/$(echo '${{ matrix.project }}' | tr '[:upper:]' '[:lower:]')"
          echo "IMAGE_NAME=$IMAGE_TAG" >> $GITHUB_ENV

      - name: Debug: show service folder
        run: |
          echo "Working directory: $GITHUB_WORKSPACE"
          pwd
          echo "--- src/${{ matrix.project }} contents ---"
          ls -al src/${{ matrix.project }}
          echo
          test -f "src/${{ matrix.project }}/Dockerfile" && echo "✔ Dockerfile found" || (echo "❌ Dockerfile missing!" && exit 1)

      - name: Build Docker image (verbose)
        run: |
          docker build \
            --progress=plain \
            --file src/${{ matrix.project }}/Dockerfile \
            --tag "$IMAGE_NAME" \
            src/${{ matrix.project }}