name: Build & Publish Services

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [ InventoryService, NotificationService, OrderService, ProductService, UserService ]
        # map each service to its API folder and its Docker tag suffix
        api-dir: [
          src/InventoryService/InventoryService.API,
          src/NotificationService/NotificationService.API,
          src/OrderService/OrderService.API,
          src/ProductService/ProductService.API,
          src/UserService/UserService.API
        ]
        tag-suffix: [ inventoryservice, notificationservice, orderservice, productservice, userservice ]

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up QEMU (for cross-platform)
        uses: docker/setup-qemu-action@v2

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push ${{ matrix.service }}
        uses: docker/build-push-action@v4
        with:
          context: ${{ matrix.api-dir }}
          file: ${{ matrix.api-dir }}/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ matrix.tag-suffix }}:latest
            ghcr.io/${{ github.repository_owner }}/${{ matrix.tag-suffix }}:${{ github.sha }}
